.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.33.0 */

glabel D_00157A00
    /* 00157A00 */ .space 0x148

glabel D_00157B48
    /* 00157B48 */ .space 0x08

glabel D_00157B50
    /* 00157B50 */ .space 0x20

glabel D_00157B70
    /* 00157B70 */ .space 0x400

glabel D_00157F70
    /* 00157F70 */ .space 0x08

glabel D_00157F78
    /* 00157F78 */ .space 0x408

glabel D_00158380
    /* 00158380 */ .space 0x40

glabel D_001583C0
    /* 001583C0 */ .space 0x110

glabel D_001584D0
    /* 001584D0 */ .space 0x18

glabel D_001584E8
    /* 001584E8 */ .space 0x18

glabel D_00158500
    /* 00158500 */ .space 0x140

glabel D_00158640
    /* 00158640 */ .space 0x140

glabel D_00158780
    /* 00158780 */ .space 0x80

glabel D_00158800
    /* 00158800 */ .space 0x80

glabel D_00158880
    /* 00158880 */ .space 0x40

glabel D_001588C0
    /* 001588C0 */ .space 0x14

glabel D_001588D4
    /* 001588D4 */ .space 0x04

glabel D_001588D8
    /* 001588D8 */ .space 0x08

glabel D_001588E0
    /* 001588E0 */ .space 0x04

glabel D_001588E4
    /* 001588E4 */ .space 0x08

glabel D_001588EC
    /* 001588EC */ .space 0x14

glabel D_00158900
    /* 00158900 */ .space 0x180

glabel D_00158A80
    /* 00158A80 */ .space 0x80

glabel D_00158B00
    /* 00158B00 */ .space 0x800

glabel D_00159300
    /* 00159300 */ .space 0x800

glabel D_00159B00
    /* 00159B00 */ .space 0x800

glabel D_0015A300
    /* 0015A300 */ .space 0x40

glabel D_0015A340
    /* 0015A340 */ .space 0x08

glabel D_0015A348
    /* 0015A348 */ .space 0x38

glabel D_0015A380
    /* 0015A380 */ .space 0xC40

glabel D_0015AFC0
    /* 0015AFC0 */ .space 0x40

glabel D_0015B000
    /* 0015B000 */ .space 0x10

glabel D_0015B010
    /* 0015B010 */ .space 0x4E0

glabel D_0015B4F0
    /* 0015B4F0 */ .space 0x390

glabel D_0015B880
    /* 0015B880 */ .space 0x200

glabel D_0015BA80
    /* 0015BA80 */ .space 0x28

glabel D_0015BAA8
    /* 0015BAA8 */ .space 0x18

glabel D_0015BAC0
    /* 0015BAC0 */ .space 0x40

glabel D_0015BB00
    /* 0015BB00 */ .space 0x40

glabel D_0015BB40
    /* 0015BB40 */ .space 0x40

glabel D_0015BB80
    /* 0015BB80 */ .space 0x40

glabel D_0015BBC0
    /* 0015BBC0 */ .space 0x40

glabel D_0015BC00
    /* 0015BC00 */ .space 0x40

glabel D_0015BC40
    /* 0015BC40 */ .space 0x100

glabel D_0015BD40
    /* 0015BD40 */ .space 0x08

glabel D_0015BD48
    /* 0015BD48 */ .space 0x1F8

glabel D_0015BF40
    /* 0015BF40 */ .space 0x28

glabel D_0015BF68
    /* 0015BF68 */ .space 0x18

glabel D_0015BF80
    /* 0015BF80 */ .space 0x1080

glabel D_0015D000
    /* 0015D000 */ .space 0x200

glabel D_0015D200
    /* 0015D200 */ .space 0x08

glabel D_0015D208
    /* 0015D208 */ .space 0x08

glabel D_0015D210
    /* 0015D210 */ .space 0x08

glabel D_0015D218
    /* 0015D218 */ .space 0x08

glabel D_0015D220
    /* 0015D220 */ .space 0x08

glabel D_0015D228
    /* 0015D228 */ .space 0x18

glabel D_0015D240
    /* 0015D240 */ .space 0x2000

glabel D_0015F240
    /* 0015F240 */ .space 0x400

glabel D_0015F640
    /* 0015F640 */ .space 0x08

glabel D_0015F648
    /* 0015F648 */ .space 0x238

glabel D_0015F880
    /* 0015F880 */ .space 0x40

glabel D_0015F8C0
    /* 0015F8C0 */ .space 0x40

glabel D_0015F900
    /* 0015F900 */ .space 0x40

glabel D_0015F940
    /* 0015F940 */ .space 0x04

glabel D_0015F944
    /* 0015F944 */ .space 0x04

glabel D_0015F948
    /* 0015F948 */ .space 0x04

glabel D_0015F94C
    /* 0015F94C */ .space 0x04

glabel D_0015F950
    /* 0015F950 */ .space 0x04

glabel D_0015F954
    /* 0015F954 */ .space 0x04

glabel D_0015F958
    /* 0015F958 */ .space 0x68

glabel D_0015F9C0
    /* 0015F9C0 */ .space 0x24

glabel D_0015F9E4
    /* 0015F9E4 */ .space 0x11C

glabel D_0015FB00
    /* 0015FB00 */ .space 0x40

glabel D_0015FB40
    /* 0015FB40 */ .space 0x28

glabel D_0015FB68
    /* 0015FB68 */ .space 0x28

glabel D_0015FB90
    /* 0015FB90 */ .space 0x30

glabel D_0015FBC0
    /* 0015FBC0 */ .space 0x10

glabel D_0015FBD0
    /* 0015FBD0 */ .space 0x08

glabel D_0015FBD8
    /* 0015FBD8 */ .space 0x14

glabel D_0015FBEC
    /* 0015FBEC */ .space 0x6BD

glabel D_001602A9
    /* 001602A9 */ .space 0x1300

glabel D_001615A9
    /* 001615A9 */ .space 0x199F

glabel D_00162F48
    /* 00162F48 */ .space 0x50

glabel D_00162F98
    /* 00162F98 */ .space 0x28

glabel D_00162FC0
    /* 00162FC0 */ .space 0x80

glabel D_00163040
    /* 00163040 */ .space 0xC0

glabel D_00163100
    /* 00163100 */ .space 0x5A9

glabel D_001636A9
    /* 001636A9 */ .space 0x1B17

glabel D_001651C0
    /* 001651C0 */ .space 0x180

glabel D_00165340
    /* 00165340 */ .space 0x80

glabel D_001653C0
    /* 001653C0 */ .space 0x40

glabel D_00165400
    /* 00165400 */ .space 0x40

glabel D_00165440
    /* 00165440 */ .space 0x200

glabel D_00165640
    /* 00165640 */ .space 0x10

glabel D_00165650
    /* 00165650 */ .space 0x110

glabel D_00165760
    /* 00165760 */ .space 0x158

glabel D_001658B8
    /* 001658B8 */ .space 0x81C

glabel D_001660D4
    /* 001660D4 */ .space 0x04

glabel D_001660D8
    /* 001660D8 */ .space 0x04

glabel D_001660DC
    /* 001660DC */ .space 0x83C

glabel D_00166918
    /* 00166918 */ .space 0x11B8

glabel D_00167AD0
    /* 00167AD0 */ .space 0x04

glabel D_00167AD4
    /* 00167AD4 */ .space 0x04

glabel D_00167AD8
    /* 00167AD8 */ .space 0x04

glabel D_00167ADC
    /* 00167ADC */ .space 0x01

glabel D_00167ADD
    /* 00167ADD */ .space 0x01

glabel D_00167ADE
    /* 00167ADE */ .space 0x02

glabel D_00167AE0
    /* 00167AE0 */ .space 0x10

glabel D_00167AF0
    /* 00167AF0 */ .space 0x15C

glabel D_00167C4C
    /* 00167C4C */ .space 0x34

glabel D_00167C80
    /* 00167C80 */ .space 0x2A90
