.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.33.0 */

glabel D_0013A390
    /* 3A590 0013A390 80A21300 */ .word func_0013A280
    /* 3A594 0013A394 A0A21300 */ .word func_0013A2A0
.size D_0013A390, . - D_0013A390

glabel D_0013A398
    /* 3A598 0013A398 00000000 */ .word 0x00000000
    /* 3A59C 0013A39C 00000000 */ .word 0x00000000
.size D_0013A398, . - D_0013A398
