.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.33.0 */

glabel D_00156300
    /* 00156300 */ .space 0xE88

glabel D_00157188
    /* 00157188 */ .space 0x208

glabel D_00157390
    /* 00157390 */ .space 0x1CC

glabel D_0015755C
    /* 0015755C */ .space 0xB8

glabel D_00157614
    /* 00157614 */ .space 0x3EC
