.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_0013A280
    /* 3A480 0013A280 1600043C */  lui        $a0, %hi(D_00165650)
    /* 3A484 0013A284 1300053C */  lui        $a1, %hi(func_001303F0)
    /* 3A488 0013A288 1600063C */  lui        $a2, %hi(D_00165640)
    /* 3A48C 0013A28C 50568424 */  addiu      $a0, $a0, %lo(D_00165650)
    /* 3A490 0013A290 F003A524 */  addiu      $a1, $a1, %lo(func_001303F0)
    /* 3A494 0013A294 10020408 */  j          func_00100840
    /* 3A498 0013A298 4056C624 */   addiu     $a2, $a2, %lo(D_00165640)
.size func_0013A280, . - func_0013A280
    /* 3A49C 0013A29C 00000000 */  nop

glabel func_0013A2A0
    /* 3A4A0 0013A2A0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 3A4A4 0013A2A4 1600043C */  lui        $a0, %hi(D_00165760)
    /* 3A4A8 0013A2A8 60578424 */  addiu      $a0, $a0, %lo(D_00165760)
    /* 3A4AC 0013A2AC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 3A4B0 0013A2B0 0CC8040C */  jal        func_00132030
    /* 3A4B4 0013A2B4 2D288000 */   daddu     $a1, $a0, $zero
    /* 3A4B8 0013A2B8 1600043C */  lui        $a0, %hi(D_00165760)
    /* 3A4BC 0013A2BC 60578424 */  addiu      $a0, $a0, %lo(D_00165760)
    /* 3A4C0 0013A2C0 6CC7040C */  jal        func_00131DB0
    /* 3A4C4 0013A2C4 2D288000 */   daddu     $a1, $a0, $zero
    /* 3A4C8 0013A2C8 1600043C */  lui        $a0, %hi(D_00166918)
    /* 3A4CC 0013A2CC 1600053C */  lui        $a1, %hi(D_00165760)
    /* 3A4D0 0013A2D0 18698424 */  addiu      $a0, $a0, %lo(D_00166918)
    /* 3A4D4 0013A2D4 6057A524 */  addiu      $a1, $a1, %lo(D_00165760)
    /* 3A4D8 0013A2D8 0A6A040C */  jal        func_0011A828
    /* 3A4DC 0013A2DC B8110624 */   addiu     $a2, $zero, 0x11B8
    /* 3A4E0 0013A2E0 1600043C */  lui        $a0, %hi(D_00167AD0)
    /* 3A4E4 0013A2E4 2D280000 */  daddu      $a1, $zero, $zero
    /* 3A4E8 0013A2E8 D07A8424 */  addiu      $a0, $a0, %lo(D_00167AD0)
    /* 3A4EC 0013A2EC 786A040C */  jal        func_0011A9E0
    /* 3A4F0 0013A2F0 7C010624 */   addiu     $a2, $zero, 0x17C
    /* 3A4F4 0013A2F4 11000424 */  addiu      $a0, $zero, 0x11
    /* 3A4F8 0013A2F8 1600033C */  lui        $v1, %hi(D_00167AD0)
    /* 3A4FC 0013A2FC D07A64AC */  sw         $a0, %lo(D_00167AD0)($v1)
    /* 3A500 0013A300 1600053C */  lui        $a1, %hi(D_00167AD0)
    /* 3A504 0013A304 67000364 */  daddiu     $v1, $zero, 0x67
    /* 3A508 0013A308 2D300000 */  daddu      $a2, $zero, $zero
    /* 3A50C 0013A30C 00016434 */  ori        $a0, $v1, 0x100
    /* 3A510 0013A310 D07AA524 */  addiu      $a1, $a1, %lo(D_00167AD0)
    /* 3A514 0013A314 1600033C */  lui        $v1, %hi(D_00167AD8)
    /* 3A518 0013A318 D87A64AC */  sw         $a0, %lo(D_00167AD8)($v1)
    /* 3A51C 0013A31C FF7F033C */  lui        $v1, (0x7FFFFFFF >> 16)
    /* 3A520 0013A320 FFFF6434 */  ori        $a0, $v1, (0x7FFFFFFF & 0xFFFF)
    /* 3A524 0013A324 1600033C */  lui        $v1, %hi(D_00167AF0)
    /* 3A528 0013A328 F07A64AC */  sw         $a0, %lo(D_00167AF0)($v1)
    /* 3A52C 0013A32C 05000424 */  addiu      $a0, $zero, 0x5
  .L0013A330:
    /* 3A530 0013A330 7800A4AC */  sw         $a0, 0x78($a1)
    /* 3A534 0013A334 0800C624 */  addiu      $a2, $a2, 0x8
    /* 3A538 0013A338 7C00A4AC */  sw         $a0, 0x7C($a1)
    /* 3A53C 0013A33C 4000C32C */  sltiu      $v1, $a2, 0x40
    /* 3A540 0013A340 8000A4AC */  sw         $a0, 0x80($a1)
    /* 3A544 0013A344 8400A4AC */  sw         $a0, 0x84($a1)
    /* 3A548 0013A348 8800A4AC */  sw         $a0, 0x88($a1)
    /* 3A54C 0013A34C 8C00A4AC */  sw         $a0, 0x8C($a1)
    /* 3A550 0013A350 9000A4AC */  sw         $a0, 0x90($a1)
    /* 3A554 0013A354 9400A4AC */  sw         $a0, 0x94($a1)
    /* 3A558 0013A358 F5FF6014 */  bnez       $v1, .L0013A330
    /* 3A55C 0013A35C 2000A524 */   addiu     $a1, $a1, 0x20
    /* 3A560 0013A360 1600043C */  lui        $a0, %hi(D_00167ADC)
    /* 3A564 0013A364 1600033C */  lui        $v1, %hi(D_00167ADD)
    /* 3A568 0013A368 DC7A80A0 */  sb         $zero, %lo(D_00167ADC)($a0)
    /* 3A56C 0013A36C DD7A60A0 */  sb         $zero, %lo(D_00167ADD)($v1)
    /* 3A570 0013A370 1600043C */  lui        $a0, %hi(D_00167ADE)
    /* 3A574 0013A374 1600033C */  lui        $v1, %hi(D_00167AE0)
    /* 3A578 0013A378 DE7A80A4 */  sh         $zero, %lo(D_00167ADE)($a0)
    /* 3A57C 0013A37C E07A60AC */  sw         $zero, %lo(D_00167AE0)($v1)
    /* 3A580 0013A380 0000BFDF */  ld         $ra, 0x0($sp)
    /* 3A584 0013A384 0800E003 */  jr         $ra
    /* 3A588 0013A388 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0013A2A0, . - func_0013A2A0
    /* 3A58C 0013A38C 00000000 */  nop
